### ISSUE TITLE
 input source "sf.ethereum.type.v1.Block" not supported

### ISSUE THREAD

**Issue by rphansen91** [streamingfast/substreams-template#15]
It looks like this was addressed with commit https://github.com/streamingfast/substreams-template/commit/7f37a762ec71242c13602d2d2e8701dec267e211

However, this was never released so the following command from documentation fails
https://substreams.streamingfast.io/getting-started/your-first-stream#run-your-first-stream

```
substreams run -e api-dev.streamingfast.io:443 \
   https://github.com/streamingfast/substreams-template/releases/download/v0.1.0/substreams-template-v0.1.0.spkg \
   map_transfers \
   --start-block 12292922 \
   --stop-block +1
   
   
Error: rpc error: code = Unknown desc = input source "sf.ethereum.type.v1.Block" not supported, only "sf.ethereum.type.v2.Block" and "sf.substreams.v1.Clock" are valid
```

**Comment by maoueh** [comment]
`sf.ethereum.type.v2.Block` was the change to perform, the template has since been updated to use this block v2.

Sorry for letting this unanswered so long.

**Comment by shishirkakhandki** [comment]
Hi @maoueh , I have been trying to run the substreams template for the erc721 contract using the steps mentioned in the read me attached. I have followed all the installation steps correctly to the best of my knowledge and they have executed without error. But when I tried to run the final run command - `substreams run -e api-dev.streamingfast.io:443 substreams.yaml map_transfers --start-block 12292922 --stop-block +1`, I am getting this error again -  
`Connected - Progress messages received: 0 (0/sec)
Backprocessing history up to requested start block 12292922:
(hit 'm' to switch display mode)

Error: rpc error: code = Unimplemented desc = unknown service sf.substreams.v1.Stream`

Can you please help? Thanks!

**Comment by maoueh** [comment]
@shishirkakhandki Update your `Substreams` CLI to latest version.

**Comment by maoueh** [comment]
Also use endpoint `mainnet.eth.streamingfast.io:443`, `api-dev.streamingfast.io:443` is a development endpoint and should never be used.

**Comment by shishirkakhandki** [comment]
Works! Thanks a lot!
