### ISSUE TITLE
"imports" missing from substreams manifest

### ISSUE THREAD

**Issue by Pelotfr** [streamingfast/substreams-template#18]
When reading the documentation on manifests (https://substreams.streamingfast.io/developers-guide/creating-your-manifest) the example given is said to be from this repository. 

But the manifest in the documentation has an import section that the manifest in this repository does not have.

![image](https://github.com/streamingfast/substreams-template/assets/65423129/1908074f-087b-40fd-945c-524d7b82f462)

**Comment by maoueh** [comment]
Fixed in d410327a9fd223e2db51eb94266b19c9e1f3028a
