### ISSUE TITLE
Error: validate request: output module must be of kind 'map'

### ISSUE THREAD

**Issue by fospring** [streamingfast/substreams-template#19]
when I run command:
```sh
substreams run -e mainnet.eth.streamingfast.io:443 substreams.yaml store_transfers --start-block 12292922 --stop-block +1
```
it renturn err:
`Error: validate request: output module must be of kind 'map'`, git commit hash is: `3b658a1c3b2f2d986b5203f5d9f1fb22a17e9892` at defaut branch
<img width="1444" alt="image" src="https://github.com/streamingfast/substreams-template/assets/19633691/f43d0eec-649c-4759-9dff-cd44269ed168">

**Comment by maoueh** [comment]
Sorry, the README was wrong running `store_transfers` directly is not possible anymore. The streamed out module must of kind `map`.

I've removed mention of running `store_transfers` directly.
